// 자동 생성: 한국어 문구 → 영어. {} 와 printf 자리표시는 같은 순서로 대응한다.
enum LocTable {
    static let english: [String: String] = [
        "계정 기본값": "Account default",
        "Claude Code에 설정된 모델": "Model set in Claude Code",
        "가장 뛰어남 · 느리고 사용량 많음": "Most capable · slower, uses more",
        "최신 Opus": "Latest Opus",
        "균형 · 추천": "Balanced · recommended",
        "빠름 · 사용량 적음": "Fast · uses less",
        "가장 빠름 · 간단한 편집": "Fastest · simple edits",
        "자동 (모델 기본)": "Auto (model default)",
        "낮음 · 빠름": "Low · fast",
        "보통": "Medium",
        "높음": "High",
        "매우 높음": "Very high",
        "최대 · 가장 깊게": "Max · deepest",
        "Claude 플랜 (Pro/Max 로그인)": "Claude plan (Pro/Max login)",
        "API 키": "API key",
        "계정 기본 모델": "Account default model",
        "중지됨": "Stopped",
        "Claude API 키를 먼저 설정하세요.": "Set your Claude API key first.",
        "Claude Code가 설치되어 있지 않습니다. claude.com/claude-code 에서 설치 후 로그인하세요.": "Claude Code is not installed. Install it from claude.com/claude-code and log in.",
        "Claude에 연결 중…": "Connecting to Claude…",
        "\n편집 도구 이름은 mcp__easycut__ 로 시작합니다. 이 앱 편집 외의 작업(파일 수정, 명령 실행)은 하지 않습니다.": "\nEditing tool names start with mcp__easycut__. Do nothing outside editing in this app (no file edits, no commands).",
        "Claude Code 실행 실패: {}": "Failed to run Claude Code: {}",
        "생각 중…": "Thinking…",
        "실행: {}": "Running: {}",
        "Claude 오류": "Claude error",
        "Claude 로그인이 필요합니다. 터미널에서 claude 를 실행하고 /login 으로 Pro/Max 계정에 로그인한 뒤 다시 시도하세요.": "You need to log in to Claude. Run claude in Terminal, log in to your Pro/Max account with /login, then try again.",
        "요청이 거절되었습니다. {}": "The request was refused. {}",
        "응답이 너무 길어 중간에 끊겼습니다.": "The reply was too long and got cut off.",
        "작업 단계가 너무 많아 멈췄습니다. 요청을 나눠 주세요.": "Stopped: too many steps. Please split your request.",
        "말 삭제": "Delete words",
        "구간 삭제": "Delete range",
        "무음 제거": "Remove silences",
        "군더더기 제거": "Remove filler words",
        "분할": "Split",
        "속도 변경": "Change speed",
        "클립 속성": "Clip properties",
        "클립 삭제": "Delete clip",
        "클립 이동": "Move clip",
        "텍스트 추가": "Add text",
        "자막 생성": "Generate captions",
        "자막 편집": "Edit captions",
        "자막 스타일": "Caption style",
        "화면 크기": "Canvas size",
        "재생헤드 이동": "Move playhead",
        "재생 속도": "Playback speed",
        "음성 인식": "Transcribe",
        "되돌리기": "Undo",
        "상태 확인": "Check state",
        "대본 읽기": "Read transcript",
        "Claude 응답을 읽지 못했습니다 (HTTP {})": "Couldn't read Claude's reply (HTTP {})",
        "API 키가 올바르지 않습니다. AI 설정에서 다시 입력하세요.": "Invalid API key. Enter it again in AI settings.",
        "요청이 너무 많습니다. 잠시 후 다시 시도하세요. ({})": "Too many requests. Try again shortly. ({})",
        "Claude 서버가 혼잡합니다. 잠시 후 다시 시도하세요. ({})": "Claude servers are busy. Try again shortly. ({})",
        "Claude 오류: {}": "Claude error: {}",
        "EasyCut 영상 편집 앱을 조작합니다. 앱이 실행 중이어야 합니다. 먼저 get_project_state로 상태를 확인하세요.": "Controls the EasyCut video editor. The app must be running. Check the state first with get_project_state.",
        "EasyCut 앱이 실행 중이 아닙니다. 앱을 먼저 여세요.": "EasyCut is not running. Open the app first.",
        "EasyCut 앱에 연결할 수 없습니다. 앱이 실행 중인지 확인하세요.": "Can't connect to EasyCut. Make sure the app is running.",
        "오류: {}": "Error: {}",
        "완료:": "Done:",
        "제목:": "Title:",
        "길이 %.1f초 %d×%d 오디오:%@ 변환필요:%@ 자막:%d": "Length %.1fs %d×%d audio:%@ needs conversion:%@ captions:%d",
        "예": "Yes",
        "아니오": "No",
        "오류:": "Error:",
        "업데이트 확인…": "Check for Updates…",
        "새 프로젝트": "New Project",
        "프로젝트 열기…": "Open Project…",
        "미디어 가져오기…": "Import Media…",
        "링크로 가져오기 (유튜브 등)…": "Import from Link (YouTube etc.)…",
        "화면·얼굴 녹화…": "Record Screen & Face…",
        "저장": "Save",
        "다른 이름으로 저장…": "Save As…",
        "자동 저장": "Auto Save",
        "영상 내보내기…": "Export Video…",
        "SRT 자막 내보내기…": "Export SRT Captions…",
        "대본 텍스트 내보내기…": "Export Transcript Text…",
        "현재 장면 PNG로 저장…": "Save Current Frame as PNG…",
        "SRT 자막 가져오기…": "Import SRT Captions…",
        "실행 취소": "Undo",
        "다시 실행": "Redo",
        "타임라인": "Timeline",
        "재생헤드에서 분할  (S)": "Split at Playhead  (S)",
        "모든 트랙 분할": "Split All Tracks",
        "삭제  (⌫)": "Delete  (⌫)",
        "삭제 후 빈틈 메우기  (⌘⌫)": "Delete and Close Gap  (⌘⌫)",
        "복제  (⌘D)": "Duplicate  (⌘D)",
        "그룹으로 묶기": "Group",
        "그룹 해제": "Ungroup",
        "하나로 합치기": "Join into One",
        "구간 시작  (I)": "Mark In  (I)",
        "구간 끝  (O)": "Mark Out  (O)",
        "구간 해제  (X)": "Clear Range  (X)",
        "텍스트(제목) 추가  (T)": "Add Text (Title)  (T)",
        "트랙 추가": "Add Track",
        "빈 트랙 정리": "Remove Empty Tracks",
        "확대": "Zoom In",
        "축소": "Zoom Out",
        "전체 보기  (⇧Z)": "Zoom to Fit  (⇧Z)",
        "재생": "Playback",
        "재생 / 일시정지  (Space)": "Play / Pause  (Space)",
        "빠르게  (L)": "Faster  (L)",
        "느리게  (J)": "Slower  (J)",
        "정지  (K)": "Stop  (K)",
        "처음으로  (Home)": "Go to Start  (Home)",
        "끝으로  (End)": "Go to End  (End)",
        "이전 편집점  (↑)": "Previous Edit Point  (↑)",
        "다음 편집점  (↓)": "Next Edit Point  (↓)",
        "도구": "Tools",
        "음성 인식 (STT)": "Transcribe (STT)",
        "대본으로 자막 만들기": "Make Captions from Transcript",
        "무음 컷 (원클릭)…": "Silence Cut (One-Click)…",
        "군더더기 말 제거": "Remove Filler Words",
        "자막 추가  (C)": "Add Caption  (C)",
        "음성 인식 설정…": "Speech Recognition Settings…",
        "Claude 연결…": "Connect Claude…",
        "단축키 보기": "Keyboard Shortcuts",
        "엔진 %@ · %.1f초 · 단어 %d개 · 중간 표시 %d회": "Engine %@ · %.1fs · %d words · %d live updates",
        "미디어": "Media",
        "대본": "Transcript",
        "자막": "Captions",
        "찾을 수 없는 파일: {}": "File not found: {}",
        "미리보기 생성 실패: {}": "Preview build failed: {}",
        "영상, 오디오, 사진 파일을 선택하세요": "Choose video, audio or photo files",
        "링크 영상": "Link video",
        "준비 중…": "Preparing…",
        "{}개 파일을 가져왔습니다": "Imported {} file(s)",
        " (자막 {}개)": " ({} captions)",
        "저장하지 않은 변경 사항이 있습니다.": "You have unsaved changes.",
        "저장하지 않고 계속할까요?": "Continue without saving?",
        "저장 안 함": "Don't Save",
        "취소": "Cancel",
        "프로젝트를 열 수 없습니다: {}": "Can't open the project: {}",
        "다시 변환 중…": "Converting again…",
        "새 프로젝트.easycut": "New Project.easycut",
        "저장했습니다": "Saved",
        "저장 실패: {}": "Save failed: {}",
        "리플 삭제": "Ripple delete",
        "삭제": "Delete",
        "{}개 클립 복사": "Copied {} clip(s)",
        "트랙 {}": "Track {}",
        "묶을 클립을 2개 이상 선택하세요 (빈 곳을 끌거나 ⇧/⌘+클릭)": "Select 2 or more clips to group (drag over empty space or ⇧/⌘+click)",
        "{}개 클립을 그룹으로 묶었습니다 (⇧⌘G 해제)": "Grouped {} clips (⇧⌘G to ungroup)",
        "그룹으로 묶인 클립을 선택하세요": "Select grouped clips",
        "그룹을 풀었습니다": "Ungrouped",
        "합칠 클립을 2개 이상 선택하세요": "Select 2 or more clips to join",
        "잘린 조각 {}곳을 하나로 합침": "Joined {} cut piece(s) back together",
        "나머지 {}개는 빈틈 없이 붙여 그룹으로 묶음": "Butted the other {} clip(s) together and grouped them",
        "합칠 수 있는 클립이 없습니다 (같은 트랙에서 이웃한 클립을 선택하세요)": "Nothing to join (select neighboring clips on the same track)",
        "속도를 바꿀 클립을 선택하세요": "Select clips to change speed",
        "텍스트를 입력하세요": "Enter text",
        "트랙 1": "Track 1",
        "시작 지점 (I) {}": "Mark in (I) {}",
        "끝 지점 (O) {}": "Mark out (O) {}",
        "음성이 있는 영상/오디오를 먼저 타임라인에 올려 주세요.": "Put a video/audio clip with speech on the timeline first.",
        "이미 인식이 끝났습니다. 다시 인식할까요?": "Already transcribed. Transcribe again?",
        "기존 대본 수정 내용은 사라집니다.": "Your edits to the current transcript will be lost.",
        "다시 인식": "Transcribe Again",
        "Whisper 엔진을 찾을 수 없습니다. 최신 EasyCut을 다시 설치해 주세요.": "Whisper engine not found. Please reinstall the latest EasyCut.",
        "Whisper 준비 완료": "Whisper is ready",
        "{}에는 오디오가 없습니다.": "{} has no audio.",
        "{}: {}개 단어 인식 완료": "{}: recognized {} words",
        "음성 인식을 중지했습니다 (인식된 부분까지 남김)": "Stopped speech recognition (kept what was recognized)",
        "%d개 단어 삭제 (%.1f초 잘림)": "Deleted %d words (cut %.1fs)",
        "삭제할 무음 구간이 없습니다": "No silences to delete",
        "무음 %d곳 삭제 (%.1f초 단축)": "Deleted %d silences (%.1fs shorter)",
        "오디오 분석 실패: {} — {}": "Audio analysis failed: {} — {}",
        "잘라낼 구간이 없습니다": "Nothing to cut",
        "%@ %d곳 삭제 (%.1f초 단축)": "%@: deleted %d (%.1fs shorter)",
        "군더더기 말(음, 어…)을 찾지 못했습니다": "No filler words (um, uh…) found",
        "대본이 없습니다. 먼저 음성 인식을 실행하세요.": "No transcript. Run speech recognition first.",
        "기존 자막을 대본으로 다시 만들까요?": "Rebuild captions from the transcript?",
        "직접 수정한 자막 내용은 사라집니다.": "Captions you edited by hand will be lost.",
        "다시 만들기": "Rebuild",
        "자막 {}개 생성": "Created {} captions",
        "새 자막": "New caption",
        "자막 %d개와 영상 %.1f초 삭제": "Deleted %d captions and %.1fs of video",
        "자막 {}개 삭제 (영상 유지)": "Deleted {} captions (video kept)",
        "순서를 바꿨습니다": "Reordered",
        "SRT 자막을 읽지 못했습니다.": "Couldn't read the SRT file.",
        "자막 {}개 가져옴": "Imported {} captions",
        "자막이 없습니다.": "No captions.",
        "SRT 저장 완료": "SRT saved",
        "대본이 없습니다.": "No transcript.",
        "대본 저장 완료": "Transcript saved",
        "장면을 PNG로 저장했습니다": "Saved the frame as PNG",
        "자동 저장 실패: {}": "Auto save failed: {}",
        "저장하지 않은 프로젝트가 있습니다": "There is an unsaved project",
        "{}에 자동으로 보관된 작업(미디어 {}개, 길이 {})을 다시 열까요?": "Reopen the work auto-saved at {} ({} media, length {})?",
        "복구": "Recover",
        "버리기": "Discard",
        "복구했습니다. ⌘S로 저장하세요": "Recovered. Press ⌘S to save",
        "재생 속도 {}": "Playback speed {}",
        "1배속": "1×",
        "스냅 켬": "Snap on",
        "스냅 끔": "Snap off",
        "전체 화면": "Full screen",
        "창": "Window",
        "영역": "Area",
        "화면 녹화 권한이 필요합니다": "Screen recording permission needed",
        "시스템 설정 › 개인정보 보호 및 보안 › 화면 및 시스템 오디오 녹음에서 EasyCut을 켠 뒤, EasyCut을 다시 시작해 주세요.": "Turn on EasyCut in System Settings › Privacy & Security › Screen & System Audio Recording, then restart EasyCut.",
        "시스템 설정 열기": "Open System Settings",
        "닫기": "Close",
        "카메라": "Camera",
        "마이크": "Microphone",
        "녹화할 화면을 찾지 못했습니다.": "Couldn't find a screen to record.",
        "녹화할 창을 고르세요.": "Choose a window to record.",
        "녹화할 영역을 먼저 고르세요.": "Choose an area to record first.",
        "녹화 중 문제가 생겼습니다: {}": "A problem occurred while recording: {}",
        "카메라·마이크를 켜지 못했습니다: {}": "Couldn't turn on the camera/microphone: {}",
        "녹화를 시작하지 못했습니다: {}": "Couldn't start recording: {}",
        "{} 권한이 필요합니다": "{} permission needed",
        "시스템 설정 › 개인정보 보호 및 보안 › {}에서 EasyCut을 켜 주세요. {} 없이 녹화하려면 녹화 설정에서 {}를 끄세요.": "Turn on EasyCut in System Settings › Privacy & Security › {}. To record without the {}, turn {} off in the recording settings.",
        "녹화를 타임라인에 넣었습니다": "Added the recording to the timeline",
        "녹화를 넣었습니다 (화면 → 트랙 1, 얼굴 → 트랙 2)": "Added the recording (screen → Track 1, face → Track 2)",
        "녹화 파일을 가져오지 못했습니다: {}\n파일 위치: {}": "Couldn't import the recording: {}\nFile location: {}",
        "끌어서 녹화할 영역을 고르세요 · esc 취소": "Drag to choose the area to record · esc to cancel",
        "프레임 합성 실패": "Frame compositing failed",
        "MP4 (HEVC, 용량 작음)": "MP4 (HEVC, smaller file)",
        "MOV (ProRes, 고화질)": "MOV (ProRes, high quality)",
        "오디오만 (M4A)": "Audio only (M4A)",
        "타임라인이 비어 있습니다.": "The timeline is empty.",
        "내보내기 세션을 만들 수 없습니다.": "Couldn't create an export session.",
        "내보내기 실패: {}": "Export failed: {}",
        "이미지 저장 실패": "Image save failed",
        "최고 화질": "Best quality",
        "소리만 (M4A)": "Audio only (M4A)",
        "링크로 가져오려면 유튜브 도구(yt-dlp)가 필요합니다.\n링크 가져오기 창에서 [유튜브 도구 설치]를 눌러 주세요.": "Importing from a link needs the YouTube tool (yt-dlp).\nClick [Install YouTube tool] in the link import window.",
        "링크 확인 중…": "Checking link…",
        "다시 시도하는 중… ({}/3)": "Retrying… ({}/3)",
        "영상을 받지 못했습니다.\n": "Couldn't download the video.\n",
        "완료": "Done",
        "받는 중: {}": "Downloading: {}",
        " · 남은 시간 {}": " · {} left",
        "받는 중 {}%{}": "Downloading {}%{}",
        "합치는 중…": "Merging…",
        "사이트가 다운로드를 막았습니다. 유튜브 도구가 오래됐을 수 있어요. 링크 가져오기 창에서 [유튜브 도구 업데이트]를 눌러 주세요.": "The site blocked the download. The YouTube tool may be outdated. Click [Update YouTube tool] in the link import window.",
        "비공개 영상입니다.": "This video is private.",
        "연령 제한 영상이라 받을 수 없습니다.": "This video is age-restricted and can't be downloaded.",
        "채널 회원 전용 영상입니다.": "This video is for channel members only.",
        "DRM으로 보호된 영상은 받을 수 없습니다.": "DRM-protected videos can't be downloaded.",
        "지원하지 않는 링크입니다.": "This link isn't supported.",
        "네트워크 오류입니다. 연결을 확인하고 다시 시도하세요.": "Network error. Check your connection and try again.",
        "볼 수 없는 영상입니다. 주소가 맞는지, 삭제·비공개된 영상은 아닌지 확인하세요.": "This video isn't available. Check the address and whether it was deleted or made private.",
        "{} 파일을 열려면 ffmpeg가 필요합니다.\n터미널에서 'brew install ffmpeg'를 실행한 뒤 다시 가져오세요.": "Opening {} files needs ffmpeg.\nRun 'brew install ffmpeg' in Terminal, then import again.",
        "포장 변환 중…": "Remuxing…",
        "영상 변환 중…": "Converting video…",
        "영상 변환 중 (소프트웨어)…": "Converting video (software)…",
        "파일을 읽을 수 없습니다: {}": "Can't read the file: {}",
        "변환 중… {}%": "Converting… {}%",
        "변환 실패: {}": "Conversion failed: {}",
        "지원하지 않는 파일 형식입니다: {}": "Unsupported file format: {}",
        "영상/오디오 트랙을 찾을 수 없습니다: {}": "No video/audio track found: {}",
        "길이를 읽을 수 없습니다: {}": "Can't read the duration: {}",
        "빈 영상 생성 실패": "Failed to create blank video",
        "빈 영상 생성 실패: {}": "Failed to create blank video: {}",
        "녹화가 시작되지 않았습니다.": "Recording didn't start.",
        "화면이 녹화되지 않았습니다.": "Nothing on screen was recorded.",
        "녹화 파일을 저장하지 못했습니다: {}": "Couldn't save the recording: {}",
        "알 수 없는 오류": "Unknown error",
        "오디오를 읽을 수 없습니다": "Can't read the audio",
        "yt-dlp를 받지 못했습니다.": "Couldn't download yt-dlp.",
        "설치됨": "Installed",
        "Claude 데스크톱 설정 파일을 읽을 수 없습니다. 직접 확인해 주세요:\n{}": "Can't read the Claude Desktop config file. Please check it yourself:\n{}",
        "Claude Code가 설치되어 있지 않습니다.": "Claude Code is not installed.",
        "연결 실패: {}": "Connection failed: {}",
        "Apple 내장 (설치 불필요)": "Apple built-in (no install)",
        "Whisper (고정확도, 모델 필요)": "Whisper (high accuracy, needs model)",
        "한국어": "Korean",
        "영어": "English",
        "일본어": "Japanese",
        "중국어": "Chinese",
        "스페인어": "Spanish",
        "프랑스어": "French",
        "독일어": "German",
        "Large v3 Turbo (추천, 정확·빠름)": "Large v3 Turbo (recommended, accurate & fast)",
        "Small (가벼움)": "Small (light)",
        "Base (매우 가벼움, 정확도 낮음)": "Base (very light, less accurate)",
        "오디오 트랙이 없습니다.": "No audio track.",
        "오디오 읽기 실패: {}": "Failed to read audio: {}",
        "오디오 추출 중…": "Extracting audio…",
        "Whisper 모델이 없습니다. 설정에서 모델을 내려받아 주세요.": "No Whisper model. Download a model in settings.",
        "음성 인식 권한이 없습니다. 시스템 설정 › 개인정보 보호 및 보안 › 음성 인식에서 EasyCut을 허용해 주세요.": "No speech recognition permission. Allow EasyCut in System Settings › Privacy & Security › Speech Recognition.",
        "{} 인식을 지원하지 않습니다.": "{} recognition isn't supported.",
        " · 남은 시간 약 {}": " · about {} left",
        "음성 인식 중… ({}/{}){}": "Recognizing speech… ({}/{}){}",
        "음성 인식 오류: {}": "Speech recognition error: {}",
        "whisper-cli가 설치되어 있지 않습니다. 터미널에서 'brew install whisper-cpp'를 실행해 주세요.": "whisper-cli is not installed. Run 'brew install whisper-cpp' in Terminal.",
        "Whisper 인식 중 ({}/{}){}": "Whisper recognizing ({}/{}){}",
        "Whisper 인식 중…": "Whisper recognizing…",
        "Whisper 실행 실패 (코드 {})\n{}": "Whisper failed (code {})\n{}",
        "모델 다운로드 실패: {}": "Model download failed: {}",
        "업데이트를 확인하지 못했습니다. 인터넷 연결을 확인하세요.": "Couldn't check for updates. Check your internet connection.",
        "최신 버전을 쓰고 있습니다. (EasyCut {})": "You're on the latest version. (EasyCut {})",
        "새 버전이 나왔습니다: EasyCut {}": "A new version is available: EasyCut {}",
        "지금 쓰는 버전은 {}입니다. 지금 업데이트할까요?\n작업 중인 프로젝트는 저장한 뒤 앱이 다시 시작됩니다.\n\n{}": "You're on version {}. Update now?\nYour project will be saved and the app will restart.\n\n{}",
        "업데이트": "Update",
        "나중에": "Later",
        "이 버전 건너뛰기": "Skip This Version",
        "업데이트 파일을 받는 중…": "Downloading the update…",
        "자동으로 바꿀 수 없는 위치에서 실행 중입니다.\n열린 창에서 EasyCut을 응용 프로그램 폴더로 끌어 놓아 바꿔 주세요.": "EasyCut is running from a location it can't replace automatically.\nIn the window that opened, drag EasyCut into the Applications folder to replace it.",
        "업데이트 {}": "Update {}",
        "업데이트 받는 중…": "Downloading update…",
        "설치 준비 중…": "Preparing to install…",
        "받은 파일이 올바른 EasyCut 새 버전이 아닙니다.": "The downloaded file isn't a valid new version of EasyCut.",
        "업데이트 실패: {}\n{} 에서 직접 받을 수 있습니다.": "Update failed: {}\nYou can download it yourself at {}.",
        "업데이트 파일을 받지 못했습니다.": "Couldn't download the update file.",
        "업데이트 파일 안에 앱이 없습니다.": "No app inside the update file.",
        "{} 실패: {}": "{} failed: {}",
        "기본": "Default",
        "원": "Circle",
        "둥근 사각형": "Rounded",
        "그대로": "As is",
        "흐리게": "Blur",
        "지우기": "Remove",
        "트랙 2": "Track 2",
        "트랙 3": "Track 3",
        "말 없는 부분 다 잘라줘": "Cut all the parts with no talking",
        "'음', '어' 같은 말 빼고 자막 만들어줘": "Make captions without 'um', 'uh'",
        "처음 10초 잘라내고 나머지는 1.5배속": "Cut the first 10 seconds, rest at 1.5×",
        "자막을 노란색 글자, 외곽선으로 크게": "Make captions yellow with an outline, bigger",
        "'감사합니다'라고 말한 부분 찾아서 삭제": "Find where I said 'thank you' and delete it",
        "5초에 '오늘의 주제' 제목 넣어줘": "Add a title 'Today's topic' at 5 seconds",
        "AI 편집": "AI Editing",
        "모델": "Model",
        "추론 강도": "Reasoning effort",
        "생각 과정 보기": "Show thinking",
        "Claude 모델과 추론 강도 선택 ({})": "Choose Claude model and reasoning effort ({})",
        "연결 방식": "Connection",
        "API 키 설정…": "Set API Key…",
        "Claude 연결 도우미…": "Claude Connection Helper…",
        "대화 지우기": "Clear Conversation",
        "Claude 플랜으로 쓰려면 Claude Code가 필요합니다.": "Using your Claude plan needs Claude Code.",
        "Claude Code를 설치하고 터미널에서 claude 실행 → /login 으로 Pro/Max 계정에 로그인하면, API 키 없이 구독 플랜으로 AI 편집을 쓸 수 있습니다.": "Install Claude Code, run claude in Terminal and log in to your Pro/Max account with /login — then AI editing uses your subscription, no API key needed.",
        "Claude 연결 도우미 열기": "Open Claude Connection Helper",
        "API 키 방식으로 바꾸기": "Switch to API key",
        "말로 편집하려면 Claude API 키가 필요합니다.": "Editing by voice/text needs a Claude API key.",
        "console.anthropic.com 에서 키를 만든 뒤 아래에 붙여 넣으세요. 키는 이 Mac의 키체인에만 저장됩니다.": "Create a key at console.anthropic.com and paste it below. The key is stored only in this Mac's Keychain.",
        "키 발급 페이지 열기": "Open key page",
        "또는 Claude Code/데스크톱에서 이 앱을 직접 조작할 수도 있습니다.": "Or control this app directly from Claude Code / Claude Desktop.",
        "Claude에 연결하는 방법 보기": "How to connect Claude",
        "이렇게 말해 보세요": "Try saying",
        "중지": "Stop",
        "터미널에서  claude  →  /login": "In Terminal:  claude  →  /login",
        "로그인하기": "Log In",
        "무엇을 편집할까요? (Enter로 보내기)": "What should I edit? (Enter to send)",
        "모든 AI 편집은 ⌘Z로 되돌릴 수 있습니다": "Every AI edit can be undone with ⌘Z",
        "생각 과정": "Thinking",
        "Claude API 키": "Claude API Key",
        "키가 저장되어 있습니다. 새 키를 넣으면 바뀝니다.": "A key is saved. Enter a new key to replace it.",
        "키를 붙여 넣으세요.": "Paste your key.",
        "키 삭제": "Delete Key",
        "Claude 연결": "Connect Claude",
        "Claude Pro/Max 구독이 있으면 API 키 없이 AI 편집을 쓸 수 있습니다. 아래 순서대로 한 번만 설정하세요.": "With a Claude Pro/Max subscription you can use AI editing without an API key. Set it up once, in this order.",
        "Claude Code 설치": "Install Claude Code",
        "다시 설치": "Reinstall",
        "설치하기": "Install",
        "확인": "Check",
        "Claude 계정 로그인 (Pro/Max)": "Log in to Claude (Pro/Max)",
        "로그인 창 열기": "Open Login Window",
        "Claude 로그인": "Claude Login",
        "확인 중…": "Checking…",
        "로그인 확인": "Check Login",
        "아직 로그인되지 않았습니다. [로그인 창 열기]로 로그인해 주세요.": "Not logged in yet. Log in with [Open Login Window].",
        "연결 완료! 이제 AI 탭에서 말로 편집할 수 있습니다.": "Connected! You can now edit by talking in the AI tab.",
        "앱 안에서 AI 편집 (AI 탭)": "AI editing inside the app (AI tab)",
        "Claude 데스크톱 앱에서 EasyCut 조작": "Control EasyCut from the Claude Desktop app",
        "다시 연결": "Reconnect",
        "연결하기": "Connect",
        "Claude 데스크톱을 완전히 종료(⌘Q) 후 다시 열면 EasyCut 도구가 보입니다.": "Quit Claude Desktop completely (⌘Q) and reopen it to see the EasyCut tools.",
        "Claude Code(터미널)에서 EasyCut 조작": "Control EasyCut from Claude Code (Terminal)",
        "Claude Code에 연결했습니다. 새 대화에서 EasyCut 도구를 쓸 수 있습니다.": "Connected to Claude Code. EasyCut tools are available in new conversations.",
        "EasyCut을 켜 둔 상태에서 Claude에게 \"EasyCut에서 무음 잘라줘\"처럼 말하면 됩니다. 연결은 이 Mac 안에서만 이뤄집니다.": "With EasyCut open, just tell Claude something like \"cut the silences in EasyCut\". The connection stays inside this Mac.",
        "Claude 앱에서 EasyCut 조작 (선택)": "Control EasyCut from Claude apps (optional)",
        "API 키로 쓰려면 AI 탭 ⚙︎ › 연결 방식 › API 키": "To use an API key: AI tab ⚙︎ › Connection › API key",
        "알림": "Notice",
        "가져오기": "Import",
        "미디어 가져오기 (⌘I)": "Import media (⌘I)",
        "녹화": "Record",
        "화면·얼굴 녹화 (⌥⌘R)": "Record screen & face (⌥⌘R)",
        "실행 취소 (⌘Z)": "Undo (⌘Z)",
        "다시 실행 (⇧⌘Z)": "Redo (⇧⌘Z)",
        "재생헤드에서 분할 (S, ⌘T)": "Split at playhead (S, ⌘T)",
        "선택 삭제 후 빈틈 메우기 (⌘⌫)": "Delete selection and close gap (⌘⌫)",
        "텍스트": "Text",
        "텍스트(제목) 추가 (T)": "Add text (title) (T)",
        "무음 컷": "Silence Cut",
        "말 없는 부분 원클릭 삭제 (⇧⌘X)": "One-click delete of parts with no talking (⇧⌘X)",
        "음성 → 텍스트 (⇧⌘R)": "Speech → text (⇧⌘R)",
        "대본으로 자막 만들기 (⇧⌘C)": "Make captions from transcript (⇧⌘C)",
        "말로 편집하기 (⌘4)": "Edit by talking (⌘4)",
        "단축키": "Shortcuts",
        "단축키 보기 (⌘/)": "Show shortcuts (⌘/)",
        "내보내기": "Export",
        "영상 내보내기 (⌘E)": "Export video (⌘E)",
        "분할 (S)": "Split (S)",
        "구간 시작 (I)": "Mark in (I)",
        "구간 끝 (O)": "Mark out (O)",
        "구간 잘라내기": "Cut Range",
        "In~Out 구간 삭제 (⌫)": "Delete the In–Out range (⌫)",
        "구간 해제 (X)": "Clear range (X)",
        "스냅 (N)": "Snap (N)",
        "재생 시 타임라인 따라가기": "Follow playhead while playing",
        "트랙 낮게": "Shorter tracks",
        "트랙 높게": "Taller tracks",
        "축소 (⌘-)": "Zoom out (⌘-)",
        "확대 (⌘=)": "Zoom in (⌘=)",
        "전체": "Fit",
        "전체 보기 (⇧Z)": "Zoom to fit (⇧Z)",
        "영상·오디오·사진 가져오기 (⌘I)": "Import video, audio, photos (⌘I)",
        "링크": "Link",
        "유튜브 등 영상 링크로 가져오기 (⇧⌘I)": "Import from a video link like YouTube (⇧⌘I)",
        "{}개": "{} items",
        "{} 가져오는 중": "Importing {}",
        "파일을 여기로 끌어다 놓으세요": "Drop files here",
        "타일을 타임라인으로 끌어다 놓거나 더블클릭하세요": "Drag a tile to the timeline or double-click it",
        "파일 없음": "File missing",
        "타임라인에 추가": "Add to Timeline",
        "재생헤드 위치에 추가": "Add at Playhead",
        "음성 다시 인식": "Transcribe Again",
        "Finder에서 보기": "Show in Finder",
        "프로젝트에서 제거": "Remove from Project",
        "대본→자막": "Transcript→Captions",
        "음성 인식 결과로 자막 자동 생성 (⇧⌘C)": "Generate captions from the transcript (⇧⌘C)",
        "재생헤드 위치에 자막 추가": "Add a caption at the playhead",
        "SRT 가져오기…": "Import SRT…",
        "SRT 내보내기…": "Export SRT…",
        "자막 모두 삭제": "Delete All Captions",
        "자막을 지우면 영상도 함께 삭제": "Deleting a caption also deletes its video",
        "켜면 자막 한 줄을 지울 때 그 말이 나오는 영상 구간도 잘려 나갑니다. 목록에서 줄을 끌어 순서를 바꾸면 영상도 함께 옮겨집니다.": "When on, deleting a caption line also cuts the video where it's spoken. Dragging lines in the list to reorder moves the video too.",
        "자막이 없습니다": "No captions",
        "음성 인식 후 [대본→자막]을 누르거나\n+ 로 직접 추가하세요.": "After transcribing, click [Transcript→Captions]\nor add one with +.",
        "자막과 그 구간 영상 삭제": "Delete caption and its video",
        "자막만 삭제": "Delete caption only",
        "크기": "Size",
        "글꼴": "Font",
        "시스템 (애플 SD 산돌고딕)": "System (Apple SD Gothic)",
        "굵게": "Bold",
        "외곽선": "Outline",
        "글자": "Text",
        "배경": "Background",
        "위치": "Position",
        "아래": "Bottom",
        "위": "Top",
        "가운데": "Middle",
        "빠른 스타일": "Quick styles",
        "노랑": "Yellow",
        "흰+외곽": "White+outline",
        "클립": "Clip",
        "시작 {} · 길이 {}": "Start {} · length {}",
        "내용": "Content",
        "속도 (최대 20배)": "Speed (up to 20×)",
        "오디오": "Audio",
        "볼륨": "Volume",
        "소리 켜기": "Unmute",
        "음소거": "Mute",
        "화면": "Picture",
        "가로 위치": "Horizontal",
        "세로 위치": "Vertical",
        "불투명도": "Opacity",
        "모양": "Shape",
        "인물 배경": "Background",
        "사람만 남기고 뒤 배경을 흐리게 하거나 지웁니다 (얼굴 카메라에 알맞음)": "Keep the person and blur or remove the background behind them (great for a face camera)",
        "마우스 클릭 강조 ({}번)": "Highlight mouse clicks ({})",
        "화면 배치": "Layout",
        "전환 (페이드)": "Transition (fade)",
        "페이드 인": "Fade in",
        "%.1f초": "%.1fs",
        "페이드 아웃": "Fade out",
        "복제": "Duplicate",
        "{}개 클립 선택됨": "{} clips selected",
        "한꺼번에 속도 바꾸기": "Change speed for all",
        "삭제 후 당기기": "Delete and close gap",
        "시작": "Start",
        "끝": "End",
        "시작=재생헤드": "Start = playhead",
        "끝=재생헤드": "End = playhead",
        "전체 자막 스타일": "Caption style (all)",
        "1920×1080 (가로 FHD)": "1920×1080 (landscape FHD)",
        "3840×2160 (가로 4K)": "3840×2160 (landscape 4K)",
        "1280×720 (가로 HD)": "1280×720 (landscape HD)",
        "1080×1920 (세로 쇼츠/릴스)": "1080×1920 (vertical Shorts/Reels)",
        "1080×1080 (정사각형)": "1080×1080 (square)",
        "1080×1350 (4:5 피드)": "1080×1350 (4:5 feed)",
        "프로젝트": "Project",
        "클립을 선택하면 속도·볼륨·크기를 조절할 수 있습니다.": "Select a clip to adjust speed, volume and size.",
        "{}×{} (원본)": "{}×{} (source)",
        "프레임 레이트": "Frame rate",
        "배경색": "Background color",
        "요약": "Summary",
        "전체 길이: {}": "Total length: {}",
        "클립: {}개 · 자막: {}개": "Clips: {} · captions: {}",
        "대본 단어: {}개": "Transcript words: {}",
        "빠른 작업": "Quick actions",
        "텍스트(제목) 추가": "Add text (title)",
        "자막 추가": "Add caption",
        "현재 장면 PNG 저장": "Save current frame as PNG",
        "영상, 오디오, 사진을 여기로 끌어다 놓으세요": "Drop video, audio or photos here",
        "또는 ⌘I 로 가져오기": "or import with ⌘I",
        "{} 재생": "Play at {}",
        "처음으로 (Home)": "Go to start (Home)",
        "5초 뒤로 (⇧←)": "Back 5s (⇧←)",
        "이전 프레임 (,)": "Previous frame (,)",
        "재생/일시정지 (Space)": "Play/pause (Space)",
        "다음 프레임 (.)": "Next frame (.)",
        "5초 앞으로 (⇧→)": "Forward 5s (⇧→)",
        "끝으로 (End)": "Go to end (End)",
        "미리보기 자막 표시": "Show captions in preview",
        "미리보기 볼륨": "Preview volume",
        "재생 중인 소리 크기 — 막대가 움직이는데 안 들리면 Mac 출력 장치/음량을 확인하세요": "Level of the sound playing — if the bar moves but you hear nothing, check your Mac's output device/volume",
        "재생 속도 (최대 20배속) — [ 느리게, ] 빠르게, \\ 1배속": "Playback speed (up to 20×) — [ slower, ] faster, \\ 1×",
        "화면·얼굴 녹화": "Record Screen & Face",
        "화면과 얼굴(카메라)을 따로 녹화해 끝나면 타임라인에 나란히 넣습니다. 화면은 트랙 1, 얼굴은 트랙 2 오른쪽 아래 작은 화면으로 들어가고, 목소리는 바로 음성 인식됩니다.": "Records the screen and your face (camera) separately and puts them side by side on the timeline: the screen on Track 1, your face as a small picture bottom-right on Track 2, and your voice is transcribed right away.",
        "녹화 범위": "Record",
        "녹화할 수 있는 창이 없습니다": "No windows available to record",
        "창 목록 새로고침": "Refresh window list",
        "{} × {} 영역": "{} × {} area",
        "아직 고르지 않음": "Not chosen yet",
        "영역 고르기…": "Choose Area…",
        "다시 고르기…": "Choose Again…",
        "카메라(얼굴)": "Camera (face)",
        "얼굴을 동그랗게": "Round face",
        "카메라를 찾지 못했습니다": "No camera found",
        "마우스 클릭 강조": "Highlight mouse clicks",
        "컴퓨터 소리 (별도 트랙)": "Computer audio (separate track)",
        "창 녹화에서는 그 창을 띄운 앱의 소리만 녹음됩니다": "Window recording only captures the audio of the app that owns the window",
        "마이크(목소리)": "Microphone (voice)",
        "시작하면 3초 뒤 녹화됩니다. 녹화 중에는 EasyCut 창이 숨고, 화면 오른쪽 아래 작은 창이나 단축키로 멈춥니다 (작은 창은 녹화에 찍히지 않음).\n⌥⌘P 일시정지·계속 · ⌥⌘. 정지 (다른 앱을 쓰는 중에도 동작)\n녹화 파일: 동영상 › EasyCut 녹화": "Recording starts 3 seconds after you press start. While recording, the EasyCut window hides; stop with the small window at the bottom-right or a shortcut (the small window is not recorded).\n⌥⌘P pause/resume · ⌥⌘. stop (works while using other apps)\nRecordings: Movies › EasyCut 녹화",
        "녹화 시작": "Start Recording",
        "곧 녹화 시작": "Starting soon",
        "일시정지": "Paused",
        "계속 녹화 (⌥⌘P)": "Resume (⌥⌘P)",
        "일시정지 (⌥⌘P)": "Pause (⌥⌘P)",
        "정지": "Stop",
        "정지 (⌥⌘.)": "Stop (⌥⌘.)",
        "저장 중…": "Saving…",
        "내보내기 완료!": "Export complete!",
        "· 남은 시간 약 {}": "· about {} left",
        "형식": "Format",
        "해상도": "Resolution",
        "프로젝트 크기 ({}×{})": "Project size ({}×{})",
        "자막을 영상에 입히기": "Burn captions into the video",
        "SRT 자막 파일도 함께 저장": "Also save an SRT caption file",
        "길이 {}": "Length {}",
        "출력 {}×{} · 길이 {}": "Output {}×{} · length {}",
        "내보내기…": "Export…",
        " 편집본.": " edit.",
        "음성 인식(STT) 설정": "Speech Recognition (STT) Settings",
        "언어": "Language",
        "엔진": "Engine",
        "macOS에 내장된 온디바이스 인식을 사용합니다. 인터넷 없이 동작하며, 처음 실행 시 음성 인식 권한을 허용해 주세요.": "Uses the on-device recognition built into macOS. Works offline; allow speech recognition the first time you run it.",
        "Whisper 엔진 내장됨": "Whisper engine built in",
        "Whisper 엔진: {}": "Whisper engine: {}",
        "whisper-cli가 필요합니다. 터미널에서 실행:": "whisper-cli is needed. Run in Terminal:",
        "내려받기": "Download",
        "모델 폴더 열기": "Open Model Folder",
        "재생 / 일시정지": "Play / pause",
        "빠르게 (누를수록 2·4·8·16·20배속)": "Faster (2·4·8·16·20× as you press)",
        "느리게": "Slower",
        "재생 속도 올리기 / 내리기": "Playback speed up / down",
        "1배속으로": "Back to 1×",
        "1·2·3·4·5·8·10·12·16·20배속 바로 선택": "Jump to 1·2·3·4·5·8·10·12·16·20×",
        "이전 / 다음 프레임": "Previous / next frame",
        "1초 뒤로 / 앞으로": "Back / forward 1s",
        "5초 뒤로 / 앞으로": "Back / forward 5s",
        "이전 / 다음 편집점": "Previous / next edit point",
        "처음 / 끝": "Start / end",
        "컷 편집": "Cut editing",
        "S  또는  ⌘T": "S  or  ⌘T",
        "재생헤드에서 분할 (선택 클립, 없으면 전체)": "Split at playhead (selected clips, or all)",
        "구간 시작 / 끝 지정": "Set range start / end",
        "선택 클립 삭제 (구간이 있으면 구간 잘라내기)": "Delete selected clips (or cut the range if set)",
        "삭제 후 빈틈 메우기 (리플 삭제)": "Delete and close gap (ripple delete)",
        "In/Out 구간 지우기": "Clear In/Out range",
        "클립 복사 / 잘라내기 / 재생헤드에 붙여넣기": "Copy / cut clips / paste at playhead",
        "클립 복제": "Duplicate clips",
        "모든 클립 선택": "Select all clips",
        "선택 해제": "Deselect",
        "실행 취소 / 다시 실행": "Undo / redo",
        "대본 · 자막": "Transcript · captions",
        "무음 컷 (원클릭, 음성 인식 불필요)": "Silence cut (one-click, no transcription needed)",
        "대본에서 ⌫": "⌫ in transcript",
        "선택한 말을 영상에서 잘라내기": "Cut the selected words from the video",
        "대본에서 ↩": "↩ in transcript",
        "단어 고치기": "Fix a word",
        "대본에서 ⌘F": "⌘F in transcript",
        "대본 검색": "Search transcript",
        "재생헤드에 자막 추가": "Add caption at playhead",
        "자막 탭에서 끌기": "Drag in Captions tab",
        "자막과 영상 구간째 순서 바꾸기": "Reorder captions together with their video",
        "트랙 1 클립 끌기": "Drag a Track 1 clip",
        "끼워 넣어 순서 바꾸기 (⌥+끌기 = 자유 이동)": "Insert to reorder (⌥+drag = free move)",
        "빈 곳 끌기": "Drag empty space",
        "클립 여러 개 선택 (⇧/⌘ = 기존 선택에 더하기)": "Select multiple clips (⇧/⌘ = add to selection)",
        "눈금자 끌기": "Drag the ruler",
        "시간 구간 선택 → ⌫ 잘라내기": "Select a time range → ⌫ to cut",
        "선택한 클립 그룹으로 묶기 / 풀기 (묶이면 함께 선택·이동)": "Group / ungroup selected clips (grouped clips select and move together)",
        "하나로 합치기: 잘린 조각은 한 클립으로, 나머지는 빈틈 없이 붙여 그룹으로": "Join: cut pieces become one clip, others are butted together and grouped",
        "재생헤드에 텍스트(제목) 추가": "Add text (title) at playhead",
        "타임라인 · 파일": "Timeline · files",
        "타임라인 확대 / 축소 (⌘+스크롤)": "Zoom timeline in / out (⌘+scroll)",
        "타임라인 전체 보기": "Fit whole timeline",
        "스냅(자석) 켜기/끄기": "Snap (magnet) on/off",
        "미디어 가져오기 / 링크(유튜브)로 가져오기": "Import media / import from link (YouTube)",
        "저장 / 다른 이름으로 저장": "Save / save as",
        "열기 / 새 프로젝트": "Open / new project",
        "미디어 / 대본 / 자막 / AI 탭": "Media / Transcript / Captions / AI tab",
        "이 도움말": "This help",
        "링크로 가져오기": "Import from Link",
        "유튜브 등 영상 페이지 주소를 붙여 넣으세요. 받은 파일은 ‘동영상 › EasyCut 다운로드’ 폴더에 저장됩니다.": "Paste the address of a video page such as YouTube. Downloads are saved to the 'Movies › EasyCut 다운로드' folder.",
        "화질": "Quality",
        "업로더가 올린 자막도 받기 (한국어·영어)": "Also download the uploader's captions (Korean · English)",
        "일부 구간만 받기": "Download only part",
        "시작 (예: 1:30)": "Start (e.g. 1:30)",
        "끝 (예: 5:00)": "End (e.g. 5:00)",
        "본인 영상이나 저작권자에게 이용 허락을 받은 영상만 내려받아 편집하세요.": "Only download and edit your own videos or ones you have permission to use.",
        "유튜브 도구(yt-dlp)가 필요합니다": "The YouTube tool (yt-dlp) is needed",
        "유튜브 도구 준비됨 {}": "YouTube tool ready {}",
        "유튜브 도구 설치": "Install YouTube Tool",
        "설치 실패: {}": "Install failed: {}",
        "github.com/yt-dlp 공식 배포본(약 35MB)을 받아 앱 전용 폴더에 설치합니다": "Downloads the official release from github.com/yt-dlp (about 35MB) into the app's own folder",
        "클립보드에서 붙여넣기": "Paste from Clipboard",
        "표시": "Shown",
        "숨김": "Hidden",
        "(없음)": "(none)",
        "순서를 바꿨습니다 (⌥를 누른 채 끌면 자유 이동)": "Reordered (hold ⌥ while dragging to move freely)",
        "구간 {} – {} · ⌫ 잘라내기, X 해제": "Range {} – {} · ⌫ to cut, X to clear",
        "재생헤드에서 분할  (⌘T / S)": "Split at Playhead  (⌘T / S)",
        "복사  (⌘C)": "Copy  (⌘C)",
        "그룹으로 묶기  (⌘G)": "Group  (⌘G)",
        "하나로 합치기  (⌘J)": "Join into One  (⌘J)",
        "그룹 해제  (⇧⌘G)": "Ungroup  (⇧⌘G)",
        "속도": "Speed",
        "자막과 영상 함께 삭제": "Delete Caption and Video",
        "자막만 삭제 (영상 유지)": "Delete Caption Only (Keep Video)",
        "여기에 텍스트 추가": "Add Text Here",
        "여기에 자막 추가": "Add Caption Here",
        "모든 트랙 분할  (⇧⌘T)": "Split All Tracks  (⇧⌘T)",
        "타임라인의 영상/오디오 음성을 텍스트로 변환 (⇧⌘R)": "Turn speech in timeline video/audio into text (⇧⌘R)",
        "인식 엔진/언어 설정": "Recognition engine / language settings",
        "Whisper가 설치되어 있어요. 긴 영상은 Whisper가 훨씬 빠르고 정확합니다.": "Whisper is installed. For long videos Whisper is much faster and more accurate.",
        "Whisper로 바꾸기": "Switch to Whisper",
        "아직 대본이 없습니다": "No transcript yet",
        "영상을 타임라인에 올리고 [음성 인식]을 누르면\n말한 내용이 텍스트로 나타납니다.\n\n텍스트를 선택해 ⌫ 를 누르면\n그 부분이 영상에서 잘려 나갑니다.": "Put a video on the timeline and click [Transcribe]\nto see what was said as text.\n\nSelect text and press ⌫\nto cut that part out of the video.",
        "{}개 단어 선택됨": "{} words selected",
        "단어 {}개 · 클릭=이동, 드래그=선택": "{} words · click = jump, drag = select",
        "선택 삭제": "Delete Selection",
        "선택한 단어 구간을 영상에서 잘라냄 (⌫)": "Cut the selected words from the video (⌫)",
        "말이 없는 구간을 한 번에 삭제": "Delete all parts with no talking at once",
        "군더더기": "Fillers",
        "'음', '어' 같은 군더더기 말 삭제": "Delete filler words like 'um', 'uh'",
        "자막 만들기": "Make Captions",
        "대본으로 자막 자동 생성 (⇧⌘C)": "Generate captions from the transcript (⇧⌘C)",
        "대본을 텍스트 파일로 저장": "Save the transcript as a text file",
        "Whisper 모델 받는 중… {}% ({}MB)": "Downloading Whisper model… {}% ({}MB)",
        "다 받으면 자동으로 음성 인식을 이어서 합니다. 한 번만 받으면 됩니다.": "Transcription continues automatically when the download finishes. You only download it once.",
        "더 정확하고 빠른 Whisper 음성 인식": "More accurate, faster Whisper recognition",
        "한국어 정확도가 높고 긴 영상도 빠릅니다 (2시간 ≈ 9분). 인식 모델을 한 번만 받으면 인터넷 없이 이 Mac에서 처리됩니다.": "Highly accurate (great for Korean) and fast even for long videos (2 hours ≈ 9 minutes). After a one-time model download it runs offline on this Mac.",
        "Whisper 켜기 (모델 {}MB 받기)": "Turn On Whisper (download {}MB model)",
        "인식이 잘못된 글자를 바로잡습니다. 자막을 다시 만들면 반영됩니다.": "Fix misrecognized text. Rebuild captions to apply it.",
        "선택한 {}개 단어를 영상에서 잘라내기  (⌫)": "Cut the {} selected words from the video  (⌫)",
        "단어를 선택하세요": "Select words",
        "단어 고치기  (↩)": "Fix Word  (↩)",
        "여기서 재생": "Play from Here",
        "선택 구간을 자막으로 추가": "Add Selection as Caption",
        "무음 제거…": "Remove Silences…",
        "소리 크기로 (음성 인식 불필요)": "By loudness (no transcription needed)",
        "대본 기준 (말 사이 공백)": "By transcript (gaps between words)",
        "소리 분석 중…": "Analyzing audio…",
        "말이 없는 부분을 찾아 한 번에 잘라냅니다. 잘릴 곳은 타임라인에 빨간색으로 표시됩니다.": "Finds the parts with no talking and cuts them at once. What will be cut is shown in red on the timeline.",
        "기준": "Method",
        "기준 음량": "Threshold",
        "자동": "Auto",
        "이 음량보다 작은 소리는 무음으로 봅니다. 잡음이 많으면 오른쪽(크게)으로, 작은 말소리까지 잘리면 왼쪽으로.": "Sounds quieter than this count as silence. Noisy recording → move right (louder); if quiet speech gets cut → move left.",
        "최소 무음 길이": "Minimum silence",
        "앞뒤 여유": "Padding",
        "%.2f초": "%.2fs",
        "빠른 설정": "Presets",
        "자연스럽게": "Natural",
        "빠른 템포": "Fast pace",
        "잘라낼 무음이 없습니다": "No silences to cut",
        "{}곳 · {}초 삭제": "{} places · {}s deleted",
        "{} → {}  ({}% 단축)": "{} → {}  ({}% shorter)",
        "무음 잘라내기": "Cut Silences",
        "무음": "Silence",
        "앱": "App",
        " — 편집됨": " — Edited",
        "플랜 로그인": "Plan login",
    ]
}
